Refactoring `margin-pool` Instruction Interface
jet-lab/jet-v2 pull request #102
Opened 2022-06-28 22:51 UTC by zachanon

The purpose of this PR is to refactor the instruction API to make it a bit more flexible and friendly.

### Generic Permissions
Instructions will be added and others modified to allow for any arbitrary token account owner to deposit tokens into the system. Particularly, there is added an instruction that allows repayment on a margin account debt without needing to invoke the signature of that margin account.

### Idempotent Instructions
Inspired by the draft PR by @Tristyn [here](https://github.com/jet-lab/jet-v2/pull/48), there is added a new field in the `Amount` struct, `ChangeKind`. This tuple will allow the user to specify whether to shift the existing account value by the given `Amount` or to attempt to calculate and set the value given automatically, without an exact specification of the change.

##### Example usage
```
// deposit 100 tokens
user.deposit(&mint_key, &user_token_account, Amount::tokens(100 * ONE_TOKEN))?;

// withdraw all tokens in the account
user.withdraw(&mint_key, &user_token_account, Amount::set_tokens(0))?;
```

2022-06-28 23:05 UTC, Tristyn commented
After `repay` is there a 2nd instruction I could call to update the margin account? So that it'd have the exact same behavior as `margin_repay`

2022-06-28 23:43 UTC, zachanon commented
`margin_repay` only updates the loan notes token account and does not mutate the margin account https://github.com/jet-lab/jet-v2/blob/master/programs/margin-pool/src/instructions/margin_repay.rs#L31

The difference here is repaying using funds from the margin account itself, or using an outside token account.

2022-06-30 15:59 UTC, suscd commented
The pool doesn't have permission to modify the margin account, the margin program will just notice any balance changes automatically in a normal invoke (or otherwise would have to be updated separately)

2022-07-06 21:49 UTC, dnut requested changes

2022-07-06 21:49 UTC, dnut commented on programs/margin-pool/src/instructions/margin_repay_from_wallet.rs
> +pub struct MarginRepayFromWallet<'info> {
This should be called `Repay`

2022-07-06 21:49 UTC, dnut commented on programs/margin-pool/src/instructions/margin_repay_from_wallet.rs
> +    pub margin_account: AccountLoader<'info, MarginAccount>,
This account should not be needed at all. But I think you'll need my changes from #111 for that to be possible. Anyone should be allowed to repay anyone else's loan.

2022-07-11 15:27 UTC, dnut commented on programs/margin-pool/src/instructions/margin_repay_from_wallet.rs
> +    pub margin_account: AccountLoader<'info, MarginAccount>,
#111 is merged but #138 if merged would also make this easier/cleaner to implement

2022-07-11 18:29 UTC, Tristyn commented
I'm merging master into this PR while keeping borrowing to wallet functioning

2022-07-12 13:06 UTC, dnut commented on programs/margin-pool/src/instructions/register_loan.rs
> +    /// CHECK:
We don't need these any more since `skip-lint` is enabled in Anchor.toml. Upgrade your anchor cli.
```suggestion
```

2022-07-12 17:59 UTC, zachanon commented on programs/margin-pool/src/instructions/register_loan.rs
> +    /// CHECK:
agreed, but lets fix this in a separate pr

2022-07-12 18:01 UTC, dnut commented on programs/margin-pool/src/instructions/register_loan.rs
> +    /// CHECK:
I'm skeptical of this linting feature. It's like anchor decided that anchor is the center of the universe and it's unacceptable to rely on other tools to do anything that anchor can do. There are a lot of reasons to have unchecked accounts. When you see an AccountInfo with no checks, It's already clear that the account is not being checked by anchor and you can easily look at how it is used. Usually it's being passed into some other program or library that has its own checks, and it's not meaningful to have checks at this level.

I'm not opposed to anyone adding these comments, but I find it annoying that anchor has made it a requirement to document your code in a certain way before compiling it. Often that means we end up putting these meaningless empty comments which is even worse than skipping linting.

2022-07-12 18:34 UTC, suscd requested changes

2022-07-12 18:34 UTC, suscd commented on programs/margin-pool/src/instructions/repay.rs
> +        constraint = margin_pool.vault == pool_vault.key()
use `has_one`

2022-07-12 18:34 UTC, suscd commented on programs/margin-pool/src/lib.rs
> +    pub fn deposit(ctx: Context<Deposit>, change_kind: u8, amount: u64) -> Result<()> {
why is `change_kind` a u8 instead of the enum?

2022-07-12 18:55 UTC, dnut approved these changes
Nice work.

This PR shined a light on some issues with the design of the accounting logic. Let's revisit this later to make it easier add features without introducing bugs. Particularly we should think of ways to avoid:
- conflating deposit notes with loan notes (the type system can help us here)
- letting MarginPool balance fields get inconsistent with reality (there should probably be explicit comparisons or assignment directly from the token accounts)
- using PoolAction in the wrong context

2022-07-12 19:05 UTC, zachanon commented on programs/margin-pool/src/lib.rs
> +    pub fn deposit(ctx: Context<Deposit>, change_kind: u8, amount: u64) -> Result<()> {
Issues with getting the typescript to properly serialize the enum. Judged it to be better to get the change out by making the interface types simpler than continue arguing with the typescript.

2022-07-12 19:10 UTC, zachanon commented
> Nice work.
> 
> This PR shined a light on some issues with the design of the accounting logic. Let's revisit this later to make it easier add features without introducing bugs. Particularly we should think of ways to avoid:
> 
> * conflating deposit notes with loan notes (the type system can help us here)
> * letting MarginPool balance fields get inconsistent with reality (there should probably be explicit comparisons or assignment directly from the token accounts)
> * using PoolAction in the wrong context

Agree strongly. The `Amount` conversions and `PoolAction` rounding could probably be solved via some smart abstractions to the way the `convert_amount` function works, possibly taking another sort of context enum like the `PoolAction` signifying why the conversion is being done, which will inform the rounding and conversion rate.

2022-07-13 07:53 UTC, suscd approved these changes

2022-07-13 07:53 UTC, merged