adapters own claims
jet-lab/jet-v2 pull request #111
Opened 2022-06-30 02:00 UTC by dnut

2022-06-30 21:25 UTC, Tristyn submitted a review, later dismissed

2022-06-30 21:29 UTC, suscd requested changes

2022-07-01 15:43 UTC, dnut commented on programs/margin/src/lib.rs
> +    pub fn register_unowned_position(ctx: Context<RegisterUnownedPosition>) -> Result<()> {
To create the position using the adapter result we need position token metadata to be passed as an additional account into the instruction. Margin needs special logic to find and deserialize the metadata account so it isn't required for every invocation. a few options:
- new invoke ix in margin that explicitly includes metadata account (more complicated api)
- the adapter knows about the metadata account and tells margin where to find it (poor separation of concerns)
- margin searches all remaining accounts for an appropriate metadata account (performance issues)
- the adapter tells margin which accounts it cares about and margin knows to only search the other accounts
- the client tells margin through parameters which accounts are for what purpose
 
To get rid of expect we need
- The `REQUIRED` flag is set to true to prevent the user from closing the position
- Another instruction in the adapter to unrequire or close the position

2022-07-01 16:52 UTC, suscd commented on programs/margin/src/lib.rs
> +    pub fn register_unowned_position(ctx: Context<RegisterUnownedPosition>) -> Result<()> {
> margin searches all remaining accounts for an appropriate metadata account (performance issues)

I'd recommend this, because it's easy to implement, and the performance hit is probably not too big since the number of accounts in the list is generally pretty small. Though the real performance hit more likely comes from having to do a `find_program_address` call to even determine what account to look for in the list. Given this really only applies to instructions used to initialize accounts, a small compute penalty should be fine for now.

2022-07-07 21:18 UTC, suscd approved these changes

2022-07-07 21:20 UTC, merged