Register position with fewer transactions
jet-lab/jet-v2 pull request #116
Opened 2022-07-01 14:14 UTC by rhubarbgarden

Within `deposit` function, create a new `withGetOrCreatePosition` function that
- takes an instruction array
- appends a `withRegisterPosition` instruction to the array

2022-07-01 14:16 UTC, Tristyn commented on libraries/ts/src/margin/marginAccount.ts
> +  async withRegisterPosition(instructions: TransactionInstruction[], tokenMint: Address): Promise<TransactionInstruction[]> {
You don't need to return anything because it's handled in `instructions.push(ix)` at the end of the method
```suggestion
  async withRegisterPosition(instructions: TransactionInstruction[], tokenMint: Address): Promise<void> {
```

2022-07-01 14:16 UTC, Tristyn commented on libraries/ts/src/margin/marginAccount.ts
> +    return instructions
```suggestion
```

2022-07-01 14:19 UTC, Tristyn commented on libraries/ts/src/margin/marginAccount.ts
> +  }
This method should have the behaviour as the orignal `getOrCreatePosition`. It
- loops and tries to find the position in `this.positions`
- calls `withCreatePosition` if it finds nothing.
- Don't return any position here. We just want to ensure it will exist
You could rename it to `withRegisterPositionIfNotExists` maybe, cause that's more like what it's doing

2022-07-01 14:20 UTC, Tristyn approved these changes

2022-07-06 04:40 UTC, Tristyn commented on libraries/ts/src/margin/marginAccount.ts
> +    throw new Error("Unable to register position.")
This function is called `getOrCreatePosition`, it does create the position but throws anyway

2022-07-06 04:41 UTC, Tristyn commented on libraries/ts/src/margin/marginAccount.ts
> +    await this.refresh()
There's no point to refreshing because the account only changes after the instruction is executed
```suggestion
    await this.withRegisterPosition(ixArray, tokenMint)
```

2022-07-06 04:43 UTC, Tristyn commented on libraries/ts/src/margin/pool/pool.ts
> +    await marginAccount.getOrCreatePosition(positionMint)
```suggestion
    await marginAccount.withGetOrCreatePosition(positionMint, instructions)
```

2022-07-06 04:49 UTC, Tristyn commented on libraries/ts/src/margin/pool/pool.ts
> +      destination: positionMint,
```suggestion
      destination: findDerivedAccount(this.programs.config.marginProgramId, marginAccount.address, positionMint),
```

2022-07-06 04:51 UTC, Tristyn commented on libraries/ts/src/margin/pool/pool.ts
> +    const positionMint = this.addresses.depositNoteMint
You will want to specifically use positionAddress for the call to `withDeposit` and `withUpdatePositionBalance`
```
    const positionAddress = findDerivedAccount(this.programs.config.marginProgramId, marginAccount.address, positionMint)
```

2022-07-06 04:53 UTC, Tristyn commented on libraries/ts/src/margin/pool/pool.ts
> +    const depositPosition = await marginAccount.withRegisterPositionIfNotExists(positionMint, instructions)
`depositPosition` and `loanPosition` are undefined because `withRegisterPositionIfNotExists` doesn't return anything. maybe it can derived the position address and return it?

2022-07-06 05:01 UTC, Tristyn requested changes
It's really coming together :)

Often the position mint is being passed into a instruction that needs the position token address, that would error if it executes

Could you update `marginWithdraw` as well? I didn't see it on the PR

After doing another pass and making sure it looks correct, you could try packing this and testing the transactions in the frontend? :)

2022-07-08 12:04 UTC, rhubarbgarden commented on libraries/ts/src/margin/marginAccount.ts
> +    throw new Error("Unable to register position.")
The current implementation of `getOrCreatePosition` returns an account position. This function is also only used in one implementation in `pool.ts`.

Throwing an error is necessary to prevent a type error [here](https://github.com/jet-lab/jet-v2/blob/1737f8988b9def55218f05a96c0f301f95e5316f/libraries/ts/src/margin/pool/pool.ts#L537)

2022-07-08 12:18 UTC, rhubarbgarden commented on libraries/ts/src/margin/pool/pool.ts
> +    await marginAccount.getOrCreatePosition(positionMint)
This should already be changed to `withRegisterPositionIfNotExists`

2022-07-08 16:39 UTC, closed without merging