updating tx history
jet-lab/jet-v2 pull request #125
Opened 2022-07-06 14:57 UTC by loganjross

2022-07-06 16:14 UTC, Tristyn commented on libraries/ts/src/margin/marginClient.ts
>      const instructions = ["repay", "borrow", "deposit", "withdraw"]
These need to be more specific cause you can pick up all sorts of false positives in the logs
```suggestion
    const instructionLogHeaders = [
      "> Program log: Instruction: MarginRepay", 
      "> Program log: Instruction: MarginBorrow", 
      "> Program log: Instruction: Deposit", 
      "> Program log: Instruction: Withdraw"
    ]
```

2022-07-06 16:16 UTC, Tristyn commented on libraries/ts/src/margin/marginClient.ts
>          tradeAction = instructions[i]
I think removing lowercase is possble and it's good to be as specific as possible
```suggestion
      if (transaction.meta?.logMessages?.some(logLine => logLine.includes(instructionLogHeaders[i]))) {
        tradeAction = instructionLogHeaders[i]
```

2022-07-06 16:26 UTC, Tristyn commented on libraries/ts/src/margin/marginClient.ts
> +              token.mint === NATIVE_MINT &&
Can you please review the code style doc. 
https://jetprotocol.atlassian.net/wiki/spaces/JC/pages/32801235/Typescript+Codestyle

Please test your code in a frontend or unit tests before asking for a review

It's not optional. This code won't work because `PublicKey === PublicKey` and `BN === BN` don't do anything

```suggestion
              token.mint.equals(NATIVE_MINT) &&
```

2022-07-06 16:27 UTC, Tristyn requested changes
Can you please review the code style doc. Specifically the stuff about equals
https://jetprotocol.atlassian.net/wiki/spaces/JC/pages/32801235/Typescript+Codestyle

Please test your changes in a frontend or unit tests before requesting a review because you might have found the `PublicKey === PublicKey` bug

Pls fix the failing test. `tsc` and `npm run test` from the root folder

2022-07-06 17:08 UTC, loganjross commented on libraries/ts/src/margin/marginClient.ts
> +              token.mint === NATIVE_MINT &&
token.mint is an address not a PublicKey so i'll have to compare .toString()

2022-07-06 17:08 UTC, loganjross commented on libraries/ts/src/margin/marginClient.ts
>      const instructions = ["repay", "borrow", "deposit", "withdraw"]
This would change in the future for pools vs other programs (when we have trading and stuff too right)

2022-07-06 17:11 UTC, Tristyn commented on libraries/ts/src/margin/marginClient.ts
>      const instructions = ["repay", "borrow", "deposit", "withdraw"]
Other programs would have different instruction names yes

2022-07-06 17:12 UTC, Tristyn commented on libraries/ts/src/margin/marginClient.ts
> +              token.mint === NATIVE_MINT &&
In that case it can be converted to public key quickly
`translateAddress(token.mint).equals(NATIVE_MINT)`

2022-07-07 23:57 UTC, Tristyn approved these changes

2022-07-08 00:25 UTC, merged