upgrade anchor
jet-lab/jet-v2 pull request #152
Opened 2022-07-12 22:23 UTC by dnut

- get anchor to latest 0.25
- which needs some other fixes like upgrading solana to 1.10
- couple other tweaks to make cargo happy like making tokio dependency more general
- some rust code fixes were also needed for breaking changes in the libraries

2022-07-12 23:07 UTC, suscd requested changes

2022-07-12 23:07 UTC, suscd commented on .github/workflows/devnet.yaml
> +  ANCHOR_CLI_VERSION: 0.25.0
the latest published version of anchor is `0.24.2`, so this doesn't work and breaks the integration test workflow which is falsely passing even though no tests are being run.

2022-07-12 23:11 UTC, dnut commented on .github/workflows/devnet.yaml
> +  ANCHOR_CLI_VERSION: 0.25.0
oops i assumed 0.25 was fully released since it was released on github

2022-07-12 23:13 UTC, dnut commented on .github/workflows/devnet.yaml
> +  ANCHOR_CLI_VERSION: 0.25.0
i see 0.25.0 here https://crates.io/crates/anchor-cli

2022-07-12 23:22 UTC, suscd commented on .github/workflows/devnet.yaml
> +  ANCHOR_CLI_VERSION: 0.25.0
I also see there's a `0.25` version for the npm package: https://www.npmjs.com/package/@project-serum/anchor

seems like the problem is just running the latest anchor cli

2022-07-13 06:49 UTC, suscd commented on .github/workflows/devnet.yaml
> +  ANCHOR_CLI_VERSION: 0.25.0
It's probably fine to leave the cli version at 0.24.2 for now, while the actual linked library is 0.25.

2022-07-13 07:06 UTC, suscd approved these changes

2022-07-13 07:07 UTC, merged