working on fixing the shiftBy levswap issue
jet-lab/jet-v2 pull request #265
Opened 2022-08-29 13:10 UTC by wilbarnes

2022-08-29 16:49 UTC, dnut requested changes

2022-08-29 16:49 UTC, dnut commented on programs/margin-swap/src/instructions/margin_spl_swap.rs
>      ctx.accounts.swap(amount_in, minimum_amount_out)?;
The `amount_in` parameter changes meaning here. When SetTo is used, it's no longer the `amount_in` quantity for a swap because for example SetTo 0 means "swap my full balance." So this line should change to two lines.

The most straightforward approach would be to copy the strategy used to determine the deposit amount at the end of this instruction. Check the balance of the transit source account and simply swap the full balance:
```suggestion
    let amount_in = token::accessor::amount(&ctx.accounts.transit_source_account)?;
    ctx.accounts.swap(amount_in, minimum_amount_out)?;
```

My only concern with this approach is that it assumes the transit account is empty to begin with, or that if there is a pre-existing balance, the user is happy to drain it for a swap. The same assumption is already built into `transit_destination_account`, so it seems OK to apply the same assumption to the source for now. Alternatively, we could check the balance before the withdrawal, and only swap the difference.

2022-08-29 16:49 UTC, dnut commented on programs/margin-swap/src/instructions/margin_spl_swap.rs
>      amount_in: u64,
I would probably change the name of this parameter because it actually represents the number used for withdrawal, and is not necessarily the same as the `amount_in` for the swap. Maybe `withdraw_amount` would be better since it's used for the amount parameter in the withdraw instruction.

2022-08-29 16:49 UTC, dnut commented on libraries/rust/src/ix_builder/margin_swap.rs
>          amount_in: u64,
I think we can remove `amount_in` here since TokenChange replaces it with the tokens field.

2022-08-29 20:51 UTC, jetjake approved these changes
this looks good to me

2022-08-31 11:41 UTC, Tristyn commented on libraries/ts/src/margin/pool/pool.ts
> +        .marginSwap(changeKind.changeKind, changeKind.value, minAmountOut.lamports)
This may allow anchor to correctly serialize it if you were having problems
```suggestion
        .marginSwap(changeKind.changeKind.asParam(), changeKind.value, minAmountOut.lamports)
```

2022-08-31 11:43 UTC, Tristyn reviewed
Check out my suggestions if you have trouble serializing the margin swap method

2022-08-31 12:45 UTC, loganjross commented on libraries/ts/src/margin/pool/pool.ts
> +    ) {
it doesn't exist on the TokenAmounts anymore, we tried

2022-08-31 14:13 UTC, dnut requested changes

2022-08-31 14:13 UTC, dnut commented on programs/margin-swap/src/instructions/margin_spl_swap.rs
> +                &self.transit_destination_account.key(),
Why copy the pubkey? It may be a negligible difference, but I expect this to be more costly.

2022-09-01 17:10 UTC, jetjake submitted a review, later dismissed

2022-09-01 17:22 UTC, dnut approved these changes

2022-09-01 17:29 UTC, merged