projecting risk after a margin swap
jet-lab/jet-v2 pull request #282
Opened 2022-09-07 13:48 UTC by loganjross

2022-09-07 13:50 UTC, Tristyn requested changes
Please undo the changes to package-lock.json and yarn.lock. You might've ran `npm i` instead of `yarn`

2022-09-07 16:27 UTC, eyevz requested changes

2022-09-07 16:27 UTC, eyevz commented on libraries/ts/src/margin/pool/pool.ts
> +    const riskIndicator = (totalLiabilities + requiredCollateral - (((1 + outputRequiredCollateralFactor)/outputRequiredCollateralFactor) * Math.abs(outputTokenLiabilityValue - minAmountOutValue)) +
Pretty close. The use of `abs` is not correct here. You're looking for `max(value, 0)`.

2022-09-07 16:27 UTC, eyevz commented on libraries/ts/src/margin/pool/pool.ts
> +    const totalLiabilities = marginAccount.valuation.liabilities.toNumber() + marginAmountValue;
```suggestion
    const totalLiabilities = marginAccount.valuation.liabilities.toNumber();
```
This is just the liabilities of the margin account before the swap. The adjustment for a possible borrow is contained in the expression for `riskIndicator` below.

2022-09-07 16:27 UTC, eyevz commented on libraries/ts/src/margin/pool/pool.ts
> +    const outputRequiredCollateralFactor = outputTokenPosition.loanPosition?.valueModifier.toNumber() ?? 0;
It would be a fatal error if the required collateral factors are missing. Setting them to zero won't save you because you divide by them below...

2022-09-07 16:27 UTC, eyevz commented on libraries/ts/src/margin/pool/pool.ts
> +      borrowRate: defaults.borrowRate
I suggest you return `nan` or some sentinel that indicates these values are meaningless, or modify the signature to just return the risk indicator.

After a swap, two pools have their rates affected. Even if you extracted the change in rates for the input token pool here, you'd have to separately calculate it for the output pool. We don't, or shouldn't, show the changes in pool rates caused by a swap anyway.

2022-09-07 16:27 UTC, eyevz commented on libraries/ts/src/margin/pool/pool.ts
> +    const outputTokenPrice = outputToken.prices.priceValue.toNumber();
Please confirm: "input" means token sent to the swap program, "output" means token received?

2022-09-08 13:55 UTC, loganjross commented on libraries/ts/src/margin/pool/pool.ts
> +      borrowRate: defaults.borrowRate
This makes sense but would break the frontend for now, I will add a TODO though

2022-09-08 14:15 UTC, Tristyn submitted a review, later dismissed

2022-09-08 18:02 UTC, eyevz commented on libraries/ts/src/margin/pool/pool.ts
> +    setupCheck?: boolean
Nice idea to build this in here. Will need one or two modifications below to accommodate.

2022-09-08 18:05 UTC, eyevz commented on libraries/ts/src/margin/pool/pool.ts
> +    const marginAmountValue = marginAmount * inputTokenPrice;
```suggestion
```
I think you don't need these anymore.

2022-09-08 18:08 UTC, eyevz commented on libraries/ts/src/margin/pool/pool.ts
> +    const inputRequiredCollateralFactor = inputTokenPosition.loanPosition.valueModifier.toNumber();
In setup check mode, this should be multiplied by SETUP_LEVERAGE_FRACTION.

2022-09-08 18:08 UTC, eyevz commented on libraries/ts/src/margin/pool/pool.ts
> +    const outputRequiredCollateralFactor = outputTokenPosition.loanPosition.valueModifier.toNumber();
In setup check mode, this should be multiplied by SETUP_LEVERAGE_FRACTION.

2022-09-08 18:14 UTC, eyevz commented
@loganjross what branch can I look at in the UI to see how this swap projected risk indicator is used? Are you already using it to perform the setup check, as well as forecast the risk indicator?

2022-09-09 14:58 UTC, eyevz requested changes

2022-09-09 14:58 UTC, eyevz commented on libraries/ts/src/margin/pool/pool.ts
>      const inputRequiredCollateralFactor = inputTokenPosition.loanPosition.valueModifier.toNumber()
This one also needs to be scaled when in setup check mode.

2022-09-09 15:49 UTC, eyevz approved these changes
Projected risk looks good. The rates are not projected but, as discussed, they don't need to be shown in this context and we can return to the TODO note later.

2022-09-09 16:05 UTC, Tristyn approved these changes

2022-09-09 16:52 UTC, merged