Conditionally render E2E wallet
jet-lab/jet-v2 pull request #359
Opened 2022-10-03 16:18 UTC by rhubarbgarden

Get value of `jetAppCluster` from localStorage and add E2E wallet to wallets array based on if mainnet or devnet.

2022-10-03 16:58 UTC, qiqicodes commented
When set to the "devnet" on settings, the "E2E wallet" doesn't appear on the wallet modal for the preview.
![Screen Shot 2022-10-03 at 9 50 59 AM](https://user-images.githubusercontent.com/68657634/193635239-333cbefb-47bf-49ae-849a-65c721ecdc2a.png)

The change does appear locally.
![Screen Shot 2022-09-28 at 3 28 02 PM](https://user-images.githubusercontent.com/68657634/193634932-bd323ef8-865f-4770-8ebe-604c095b4425.png)

2022-10-03 22:14 UTC, jetjake approved these changes

2022-10-03 22:14 UTC, jetjake requested changes
what about localnet?

2022-10-03 23:25 UTC, rhubarbgarden commented
@jetjake We don't use localnet at all in the UI when running E2E tests, I don't think we would need to make the E2E wallet available to localnet

2022-10-04 12:57 UTC, jetjake approved these changes

2022-10-04 13:10 UTC, merged