Constrain Order Parameters for Safety
jet-lab/jet-v2 pull request #381
Opened 2022-10-14 10:37 UTC by zachanon

No order should be placed for a non-positive amount of interest. This PR includes a check before placing an order that bond tickets > underlying tokens.

2022-10-14 15:05 UTC, zachanon commented on libraries/ts/bonds/src/bondMarket.ts
> +      maxBondTicketQty: amount.add(new BN(1)),
its a bandaid until the fix to the AAOB that gives more detailed return values allows us to properly calculate collateral. Without the +1 this instruction fails the check that interest is positive nonzero

2022-10-14 15:06 UTC, zachanon commented on programs/bonds/src/errors.rs
> +    #[msg("interest for an order should always be positive")]
Noted. For current state, alphabetical is fine. But after release, should use that practice.

2022-10-14 19:35 UTC, dnut commented on programs/bonds/src/orderbook/state.rs
> +        if max_underlying_token_qty >= max_bond_ticket_qty {
The ratio of max quantities is not the same as the price. For example you can set max_underlying_token_qty to u64::MAX and max_bond_ticket_qty to 20 with a price of 0.9. That implies a positive interest rate of around 11% that will only be considered filled once 20 bond tickets have been traded.

I would use the `limit_price` field so you can test the actual interest rate.

2022-10-14 19:37 UTC, dnut commented on tests/hosted/tests/bonds.rs
> +        max_bond_ticket_qty: 0,
The same comment I made for the other order also applies here.

This approach has the additional downside that it won't allow users to specify a borrow order in terms of bond ticket quantity. They are only allowed to do so in terms of underlying. Granted, underlying is probably what they're usually thinking about. But there may be some case like for example, they know exactly how much money they will receive in 6 months, so they just want to borrow as much money as possible today that can definitely be repaid with the income they are certain they will receive in six months.

2022-10-14 19:39 UTC, dnut requested changes
If you want to constrain the interest rate, constrain the price. Constraining max quantities will only constrain the order size, or traded volume, not the interest rate.

2022-10-24 03:47 UTC, zachanon commented
closing this PR to make a fresh branch

2022-10-24 03:47 UTC, closed without merging