Add additional period for term deposits
jet-lab/jet-v2 pull request #382
Opened 2022-10-14 10:59 UTC by zachanon

Allow loan order maturation to exceed borrow duration

2022-10-14 19:45 UTC, dnut commented on programs/bonds/src/control/state.rs
> +    /// Number of slots added to initial strike timestamp to determine loan maturity
```suggestion
    /// Number of seconds added to initial strike timestamp to determine loan maturity
```

2022-10-14 19:45 UTC, dnut commented on programs/bonds/src/control/instructions/initialize_bond_manager.rs
> +    /// Number of slots added to initial strike timestamp to determine loan maturity
```suggestion
    /// Number of seconds added to initial strike timestamp to determine loan maturity
```

2022-10-14 19:50 UTC, dnut commented on programs/bonds/src/control/state.rs
> +    pub deposit_duration: i64,
This name is a little confusing to me. I interpret it as meaning it represents the entire duration of any deposit. But it's actually only the extra delay added on to delay the redemption of staked tickets. I would probably pick some other name, something like `(ticket)?_(redemption|unstake)_(delay|latency|lag)`

2022-10-14 19:51 UTC, dnut requested changes
Looks good, just some minor wording nitpicks.

2022-10-14 19:57 UTC, dnut commented on programs/bonds/src/control/state.rs
> +    pub deposit_duration: i64,
Another thought - should we always have a guarantee that both durations are positive, and the lender duration is always at least as long? Maybe it's worth putting some kind of checks for that. For example using u64 instead of i64.

2022-10-20 07:43 UTC, zachanon commented on programs/bonds/src/control/state.rs
> +    pub deposit_duration: i64,
I like the idea of explicitly defining the two durations. Opted not to include a check, these values are staged at initialization and then should not reasonably be changed

2022-10-24 06:24 UTC, closed without merging