bonds origination fee for borrowers
jet-lab/jet-v2 pull request #430
Opened 2022-11-03 20:58 UTC by dnut

2022-11-17 19:19 UTC, eyevz commented on libraries/rust/margin/src/bonds/ix_builder.rs
> +        self.modify_manager([false as u8].into(), 8 + 32 * 14 + 2)
Can't be having those unlucky offsets ;)

2022-11-18 11:33 UTC, eyevz commented on programs/bonds/src/control/instructions/withdraw_fees.rs
> +    pub fee_destination: AccountInfo<'info>,
Is the fee destination checked against the what's been set on the bond manager? I couldn't figure out where that happens.

2022-11-18 12:31 UTC, eyevz commented on programs/bonds/src/margin/origination_fee.rs
> +        FEE_UNIT * filled_quote / (FEE_UNIT + origination_fee)
What guarantees that this is evaluated as `(u * q) / (u + f)` rather than `u * (q / (u = f))`? Is that a Rust spec, is it guaranteed for all compilers and targets?

2022-11-18 12:34 UTC, eyevz commented on programs/bonds/src/margin/origination_fee.rs
> +const FEE_UNIT: u64 = 1_000_000;
"centibeeps"? "micrumbs"? :)

2022-11-18 17:34 UTC, dnut commented on programs/bonds/src/margin/origination_fee.rs
> +        FEE_UNIT * filled_quote / (FEE_UNIT + origination_fee)
Rust guarantees left-to-right associativity of arithmetic operators with equal precedence.
https://doc.rust-lang.org/reference/expressions.html#expression-precedence

2022-11-18 17:37 UTC, dnut commented on programs/bonds/src/control/instructions/withdraw_fees.rs
> +    pub fee_destination: AccountInfo<'info>,
lol oops where are all the checks that are supposed to be on this instruction, that's not the only one missing

2022-11-21 10:04 UTC, eyevz requested changes
Some questions / comments attached.

2022-11-21 10:08 UTC, eyevz submitted a review, later dismissed
Your latest changes address the main concern I had.

2022-11-22 04:43 UTC, dnut commented on programs/bonds/src/margin/origination_fee.rs
> +        let quote = 1 + requested + (requested * origination_fee as u128) / FEE_UNIT as u128;
It's certainly doable but it's kind of arbitrary. It would be very easy to throw in a const right here. Configuring per market is a little more complicated just because you have to deal with one more parameter in several places, but it's not a big deal.

2022-11-22 14:43 UTC, dnut commented on programs/bonds/src/margin/origination_fee.rs
> +        let quote = 1 + requested + (requested * origination_fee as u128) / FEE_UNIT as u128;
> - user gets what they asked for
> - protocol gets implied origination fee plus remaining base fee?

Actually these two points are in conflict each other. The base fee would be a constant per-fill regardless of size. This *decreases* the total amount borrowed for larger numbers of fills. If the priority is to ensure users get what they requested, you'd want to simply increase the order size without assessing a base fee.

2022-11-22 18:56 UTC, eyevz commented on programs/bonds/src/margin/origination_fee.rs
> +        let quote = 1 + requested + (requested * origination_fee as u128) / FEE_UNIT as u128;
I suppose I had in mind that the base fee is the part that eats the rounding errors, instead of the origination fee or requested loan, but I get that it's hard to attach metadata to an order that can be tracked across fills.

But overall I think what you've implemented here ticks all the boxes. Let's return to questions of rounding if necessary after observing this beast in the wild.

2022-11-22 20:33 UTC, dnut commented on programs/bonds/src/margin/origination_fee.rs
> +        let quote = 1 + requested + (requested * origination_fee as u128) / FEE_UNIT as u128;
The idea is nice, but it puts the cart before the horse. You have to know how many fills are going to happen in the future to decide how much of a current fill should go to the user vs the base fee. Imagine an order is 50% filled by an order with 50% remaining on the book. How much do we deduct for the base fee now? 0? 50% of the base fee amount? 10%?

If we collect anything on the first fill, you need to know how many fills there will be in the future to figure out how much of the base fee to collect now. If you guess wrong, you defeat the intention of using it as a buffer because you run the risk of overcharging them.

So you can only be sure that it works properly if you collect later. That means you wait until the order is fully removed off the book, and assess the base fee during either the last fill or the order cancel. Just give them a little less money in the last fill - exactly enough ensure they get what they requested. This requires some additional state to be persisted for the order which introduces complexity that may not be worth it. Furthermore there is always the possibility that they cancel the order, in which case we have to decide: are they allowed to bypass the fee via cancellation, or do we create a new obligation for negligible amounts of money every time a partially filled order is cancelled?

Using a base fee to ensure they get exactly what they asked for seems possible but I don't think it's worth the complexity. Padding the order size by some constant will ensure they get *at least* what was requested, but possibly more, and it is much simpler to implement.

2022-11-30 15:57 UTC, suscd approved these changes

2022-11-30 15:57 UTC, merged