Add instruction to roll over matured `TermDeposit` accounts
jet-lab/jet-v2 pull request #551
Opened 2023-01-11 22:09 UTC by zachanon

2023-01-17 15:24 UTC, dnut requested changes

2023-01-17 15:26 UTC, dnut commented on programs/fixed-term/src/orderbook/state/lend.rs
> +pub struct LendOrderAccounts<'a, 'info> {
I see your comment

> The auto_roll_lend instruction required refactoring the logic of the margin_lend and margin_redeem_deposit instructions to accept account references, to avoid overflowing the stack.

If we can have anchor initialize the structs as part of the instruction's Accounts struct, then I don't think this will be a problem.

2023-01-18 16:14 UTC, zachanon commented on programs/fixed-term/src/orderbook/state/lend.rs
> +pub struct LendOrderAccounts<'a, 'info> {
I couldn't get that to work without blowing the stack. Too many AccountInfos

2023-01-18 16:21 UTC, zachanon commented on programs/fixed-term/src/margin/instructions/auto_roll_lend_order.rs
> +pub struct AutoRollLendOrder<'info> {
Autorolling requires a `MarginUser` account, we store the parameters in that account (for now just the appropriate limit price). Working with the constraint that I couldn't fit all the accounts needed to nest into the instruction structs, I took the option of moving the logic to take references for all instructions involved. So logic is reused, which was a goal of mine when writing this. Unfortunately we do lose the account checks of the other instructions with this approach, but otherwise we use the same logic for redemption and order placement as the standalone instructions.

2023-01-19 01:16 UTC, zachanon commented on programs/fixed-term/src/margin/instructions/auto_roll_lend_order.rs
> +        constraint = deposit.owner == margin_account.key() @ FixedTermErrorCode::WrongDepositOwner,
Is there a reason we did/do it that way? Looking at redemption logic on master, we check that the `owner` for the deposit signs [here](https://github.com/jet-lab/jet-v2/blob/master/programs/fixed-term/src/tickets/instructions/redeem_deposit.rs#L83). We skip that check in the `margin_redeem` logic, but I could not figure out why, so I removed the need for that `authority` account and just made the `owner` sign. It makes more sense conceptually to me to have the owner be a signing account, which is the `MarginAccount` not the `MarginUser`.

2023-01-19 14:27 UTC, dnut commented on programs/fixed-term/src/margin/instructions/auto_roll_lend_order.rs
> +        constraint = deposit.owner == margin_account.key() @ FixedTermErrorCode::WrongDepositOwner,
> We skip that check in the margin_redeem logic, but I could not figure out why, 

The same validation is executed transitively. The signer is validated to be the owner of the MarginUser, and the MarginUser is validated to be the owner of the TermDeposit. This means that the signer is allowed to redeem the TermDeposit, but only if it it goes through the MarginUser. It's the same concept as having the MarginAccount be an authority over things instead of the user's actual wallet. The user is delegating to some PDA so owning program can execute its own validations after checking that the user has signed.

Those are implementation details. But there is one abstract goal that is important. We can't allow a signer to redeem a TermDeposit that is being used as collateral without that user also forfeiting its value as collateral. If the margin account is considered the owner of a TermDeposit, that means they can execute the non-margin redeem instruction through an adapter invoke, which allows them to collect the money without forfeiting their collateral tokens. The program needs some way to prevent this.

One approach is the existing implementation. The MarginUser is listed as the owner. There's no way a user can get a signature from the MarginUser account, so they are forced to use the margin_redeem instruction, which forfeits the collateral before they can access the funds.

Another approach would need some other way to encode margin-specific information in the TermDeposit using additional fields. You could have the owner always be the actual signer, which means that a TermDeposit used as collateral would list the MarginAccount as the owner instead of the MarginUser. Then you would need another field to indicate whether it's being used as collateral. For example, there could be another field called margin_user in the TermDeposit that is only set if its owned by a MarginUser. If margin_user == Pubkey::default() then you assume the user does not need to forfeit collateral.

Initially I preferred option 1 because it followed the same pattern as the margin account, where the user delegates ownership to some PDA. But it is a little different because it's all encapsulated within a single program, and likewise the fixed term program doesn't actually sign with the MarginUser account. Likewise the owner account isn't technically a true signer in that case. I can see how that can be confusing. I'm not opposed to using a different approach, but we do need some way to accomplish this restriction.

2023-01-19 14:53 UTC, dnut commented on programs/fixed-term/src/margin/instructions/auto_roll_lend_order.rs
> +pub struct AutoRollLendOrder<'info> {
> Autorolling requires a MarginUser account, we store the parameters in that account
OK yeah I forgot about that and got confused

2023-01-20 17:25 UTC, zachanon commented on programs/fixed-term/src/margin/instructions/auto_roll_lend_order.rs
> +        constraint = deposit.owner == margin_account.key() @ FixedTermErrorCode::WrongDepositOwner,
In the latest commit I added checks to the vanilla redemption instruction to assert that the `TermDeposit` is not in the custody of a margin account. This should prevent the issue of a margin user redeeming deposits without proper collateral accounting.

2023-01-23 18:16 UTC, dnut commented on programs/fixed-term/src/margin/instructions/auto_roll_lend_order.rs
> +        constraint = deposit.owner == margin_account.key() @ FixedTermErrorCode::WrongDepositOwner,
I would also add an analogous check to margin redeem so you can't inadvertently burn collateral tokens that don't represent the deposit being redeemed.

2023-03-10 00:47 UTC, suscd approved these changes

2023-03-10 00:47 UTC, merged