Load associated token accounts by owner
jet-lab/jet-v2 pull request #56
Opened 2022-06-08 21:52 UTC by Tristyn

2022-06-08 23:00 UTC, jetjake requested changes
Requesting a few changes.  Feel free to argue against my positions

2022-06-08 23:00 UTC, jetjake commented on libraries/ts/src/token/associatedToken.ts
>    static async loadMultipleOrNative(
This is a pretty big method, can we break it up to more modular pieces?

2022-06-08 23:00 UTC, jetjake commented on libraries/ts/src/token/associatedToken.ts
> +    const accountInfos = await connection.getMultipleAccountsInfo(pubkeys)
this looks similar to the above code block.  Maybe good to create a modular function to reduce code duplication.

2022-06-09 15:53 UTC, Tristyn commented
I was thinking the same thing. I can address it soon

2022-06-09 15:55 UTC, jetjake approved these changes
Talked to Tristyn, we will merge this and fix later.

2022-06-09 16:06 UTC, merged