Swap/openbook referral fees + test service
jet-lab/jet-v2 pull request #695
Opened 2023-05-04 14:03 UTC by nevi-me

2023-05-04 19:51 UTC, dnut requested changes

2023-05-04 19:51 UTC, dnut commented on programs/margin-swap/src/instructions/openbook_swap.rs
> +    #[account(mut, token::authority = CONTROL_AUTHORITY)]
Isn't the control program deprecated? I thought airspaces supersede everything in there. Why can't the airspace authority or governor own this?

Also this is missing a constraint. I would validate that it is the specific account you expect to be used here, not just the authority.

2023-05-04 19:51 UTC, dnut commented on programs/margin-swap/src/instructions/route_swap.rs
> +            let accounts = remaining_accounts.take(12).cloned().collect::<Vec<_>>();
It would be nice if we didn't have to manually maintain this number, but I'm not sure how to avoid it.

2023-05-05 03:16 UTC, suscd submitted a review, later dismissed

2023-05-05 03:19 UTC, suscd commented on programs/margin-swap/src/instructions/openbook_swap.rs
> +    #[account(mut, token::authority = CONTROL_AUTHORITY)]
Sort of, but it currently owns all the token accounts any fees get collected into, so for consistency it makes sense to just also collect these there. It probably makes sense to repurpose the control program to only handle fee processing in the future.

Though I agree that this should probably check that this is the correct ATA address instead of just the owner/authority.

2023-05-05 13:10 UTC, dnut commented on programs/margin-swap/src/instructions/openbook_swap.rs
> +    #[account(mut, token::authority = CONTROL_AUTHORITY)]
It's easy to change the owner of a token account.

2023-05-19 15:05 UTC, suscd commented on programs/margin-swap/src/instructions/openbook_swap.rs
> +    #[account(mut, token::authority = CONTROL_AUTHORITY)]
The check we were referring to is an address check to validate that it's an ATA, which ensures there's only a single account that fees can be sent to

2023-05-25 17:22 UTC, suscd approved these changes

2023-05-25 17:23 UTC, merged